from __future__ import annotations

import json
import re
from pathlib import Path

from .core import DraftModule, VerificationReport
from .draft_ast import parse_draft_ast
from .execution_context import TrustedExecutionContext
from .lowering_gate import assess_lowering_eligibility
from .safety_registry import get_registry
from .operation_registry import get_operation_registry
from .transaction_contract import extract_transactions, transaction_for_operation

REGISTRY = get_registry()
OP_REGISTRY = get_operation_registry()

_LOWERING_REGISTRY = get_registry()


_SAFE_SLUG_RE = re.compile(r"[^A-Za-z0-9_.-]+")
_TS_IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def lower_to_typescript(draft: DraftModule, report: VerificationReport, out_dir: str | Path, context: TrustedExecutionContext | None = None) -> Path:
    """Generate a source-mapped TypeScript skeleton from a verifier-ready draft.

    Pre-v1 Phase 12: transaction metadata is no longer a comment-only hint.
    If the verified draft declares a transaction binding, the generated skeleton
    exposes a TransactionEnvelope and wraps the contiguous transaction operation
    segment with a host-runtime ``runTransaction`` hook.
    """
    context = context or TrustedExecutionContext.public_demo()
    gate = assess_lowering_eligibility(draft, report, context)
    if not gate.allowed:
        first = gate.findings[0] if gate.findings else None
        if first is not None:
            raise RuntimeError(f"Refusing to lower: {first.rule}: {first.message}")
        raise RuntimeError("Refusing to lower: lowering eligibility gate did not pass.")
    parsed = parse_draft_ast(draft)
    if parsed.has_critical or parsed.ast is None:
        raise RuntimeError("Refusing to lower a draft that does not parse into Strict Draft AST.")
    ast = parsed.ast

    module_slug = _safe_slug(ast.module, fallback="module")
    function_name = _safe_function_name(ast.task)
    input_type = _safe_type_name(ast.passthrough.get("input_type", "Record<string, unknown>"), "input_type")
    output_type = _safe_type_name(ast.passthrough.get("output_type", "Record<string, unknown>"), "output_type")
    return_expr = _safe_return_expr(ast.passthrough.get("return", "state"))

    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    target = out_path / f"{module_slug}.lowered.ts"

    transactions = extract_transactions(ast.to_draft_module())
    tx_by_op = {op_id: tx.id for tx in transactions for op_id in tx.includes}
    tx_by_id = {tx.id: tx for tx in transactions}

    lines: list[str] = []
    lines.append("// Generated by AiNIR public demo lowerer.")
    lines.append("// This is an auditable skeleton, not production application code.")
    lines.append("")
    lines.append("export type Result<T> = { ok: true; value: T } | { ok: false; error: string };")
    lines.append("export type OperationEnvelope = {")
    lines.append("  operationId: string;")
    lines.append("  canonicalOp: string;")
    lines.append("  effects: string[];")
    lines.append("  capabilities: string[];")
    lines.append("  policies: string[];")
    lines.append("  riskFamilies: string[];")
    lines.append("  transactionId?: string;")
    lines.append("  trustedEnvironment: string;")
    lines.append("  verificationStatus: \"passed\";")
    lines.append("};")
    lines.append("export type TransactionEnvelope = {")
    lines.append("  transactionId: string;")
    lines.append("  mode: string;")
    lines.append("  includes: string[];")
    lines.append("  trustedEnvironment: string;")
    lines.append("  verificationStatus: \"passed\";")
    lines.append("};")
    lines.append("export type ModuleEnvelope = {")
    lines.append("  moduleId: string;")
    lines.append("  workflow: string;")
    lines.append("  task: string;")
    lines.append("  trustedEnvironment: string;")
    lines.append("  verificationStatus: \"passed\";")
    lines.append("};")
    lines.append("export type HostContext = {")
    lines.append("  enforceModule?(envelope: ModuleEnvelope, state: Record<string, unknown>): Promise<void>;")
    lines.append("  enforceTransaction(envelope: TransactionEnvelope, state: Record<string, unknown>): Promise<void>;")
    lines.append("  runTransaction<T>(envelope: TransactionEnvelope, state: Record<string, unknown>, body: () => Promise<T>): Promise<T>;")
    lines.append("  enforceOperation(envelope: OperationEnvelope, state: Record<string, unknown>): Promise<void>;")
    lines.append("  callOperation(envelope: OperationEnvelope, state: Record<string, unknown>): Promise<unknown>;")
    lines.append("};")
    for t in sorted({input_type, output_type}):
        if t not in {"Record<string, unknown>", "unknown", "string", "number", "boolean"}:
            lines.append(f"export type {t} = Record<string, unknown>;")
    lines.append("")
    lines.append(f"export async function {function_name}(input: {input_type}, ctx: HostContext): Promise<Result<{output_type}>> {{")
    lines.append(f"  // workflow: {_safe_line(ast.workflow)}")
    lines.append("  const state: Record<string, unknown> = { input };")
    module_envelope = {"moduleId": ast.module, "workflow": ast.workflow, "task": ast.task, "trustedEnvironment": context.environment, "verificationStatus": "passed"}
    lines.append(f"  await ctx.enforceModule?.({json.dumps(module_envelope, ensure_ascii=False)}, state);")
    lines.append("  // Host enforcement contract: transaction-bound modules require runtime enforcement hooks.")
    lines.append("  if (!ctx.enforceTransaction || !ctx.runTransaction || !ctx.enforceOperation || !ctx.callOperation) {")
    lines.append("    return { ok: false, error: \"host_enforcement_contract_required\" };")
    lines.append("  }")
    lines.append("")

    i = 0
    ops = list(ast.operations)
    while i < len(ops):
        op_ast = ops[i]
        tx_id = tx_by_op.get(op_ast.id)
        if tx_id is None:
            _emit_operation(lines, op_ast, None, context)
            i += 1
            continue
        tx = tx_by_id[tx_id]
        tx_ops = []
        while i < len(ops) and tx_by_op.get(ops[i].id) == tx_id:
            tx_ops.append(ops[i])
            i += 1
        tx_envelope = {
            "transactionId": tx.id,
            "mode": tx.mode,
            "includes": list(tx.includes),
            "trustedEnvironment": context.environment,
            "verificationStatus": "passed",
        }
        tx_var = "tx_" + _safe_var_suffix(tx.id)
        lines.append(f"  const {tx_var}: TransactionEnvelope = {json.dumps(tx_envelope, ensure_ascii=False)};")
        lines.append(f"  await ctx.enforceTransaction({tx_var}, state);")
        lines.append(f"  await ctx.runTransaction({tx_var}, state, async () => {{")
        for nested_op in tx_ops:
            _emit_operation(lines, nested_op, tx.id, context, indent="    ")
        lines.append("  });")
        lines.append("")

    lines.append(f"  return {{ ok: true, value: {return_expr} as {output_type} }};")
    lines.append("}")
    target.write_text("\n".join(lines), encoding="utf-8")
    return target


def _emit_operation(lines: list[str], op_ast, transaction_id: str | None, context: TrustedExecutionContext, indent: str = "  ") -> None:
    op_id = _safe_operation_id(op_ast.id)
    canonical = _safe_line(OP_REGISTRY.canonical_id_for(op_ast.op) or op_ast.op)
    effects = [REGISTRY.normalize_effect(e)[0] for e in list(op_ast.effects)]
    capabilities = list(op_ast.capabilities)
    policies = list(op_ast.policies)
    risk_families = sorted(set().union(*(REGISTRY.classify_effect(e) for e in effects)) if effects else set())
    envelope = {
        "operationId": op_id,
        "canonicalOp": canonical,
        "effects": effects,
        "capabilities": capabilities,
        "policies": policies,
        "riskFamilies": risk_families,
        "trustedEnvironment": context.environment,
        "verificationStatus": "passed",
    }
    if transaction_id is not None:
        envelope["transactionId"] = transaction_id
    op_key = json.dumps(op_id)
    suffix = _safe_var_suffix(op_id)
    lines.append(f"{indent}// op: {_safe_line(op_id)}")
    lines.append(f"{indent}const envelope_{suffix}: OperationEnvelope = {json.dumps(envelope, ensure_ascii=False)};")
    lines.append(f"{indent}await ctx.enforceOperation(envelope_{suffix}, state);")
    lines.append(f"{indent}state[{op_key}] = await ctx.callOperation(envelope_{suffix}, state);")
    lines.append("")


def _safe_slug(value: str, fallback: str) -> str:
    value = _SAFE_SLUG_RE.sub("_", str(value).strip())
    value = value.strip("._-")
    if not value:
        value = fallback
    return value[:96]


def _safe_function_name(value: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", str(value))
    parts = [p for p in parts if p]
    if not parts:
        return "runTask"
    head = parts[0]
    candidate = head[:1].lower() + head[1:] + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    if not _TS_IDENTIFIER_RE.match(candidate) or candidate in REGISTRY.ts_reserved_words:
        candidate = "run" + "".join(p[:1].upper() + p[1:] for p in parts)
    if not _TS_IDENTIFIER_RE.match(candidate) or candidate in REGISTRY.ts_reserved_words:
        return "runTask"
    return candidate


def _safe_type_name(value: object, field: str) -> str:
    if not isinstance(value, str):
        raise RuntimeError(f"Refusing to lower: {field} must be a string.")
    value = value.strip()
    if value in _LOWERING_REGISTRY.lowering_allowed_types():
        return value
    raise RuntimeError(f"Refusing to lower: {field}={value!r} is not in the public demo type allowlist.")


def _safe_return_expr(value: object) -> str:
    if not isinstance(value, str):
        raise RuntimeError("Refusing to lower: return expression must be a string.")
    value = value.strip()
    if value in _LOWERING_REGISTRY.lowering_allowed_returns():
        return value
    raise RuntimeError("Refusing to lower: return expression must be one of state or input.")


def _safe_operation_id(value: str) -> str:
    if not re.match(r"^[A-Za-z][A-Za-z0-9_.-]{0,127}$", value):
        raise RuntimeError(f"Refusing to lower unsafe operation id: {value!r}")
    return value


def _safe_var_suffix(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", value)[:80]


def _safe_line(value: str) -> str:
    text = str(value).replace("*/", "* /").replace("/*", "/ *")
    return text.replace("\r", " ").replace("\n", " ").replace("\t", " ")[:240]
